#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=4Gb
#PBS -l ncpus=1
#PBS -j oe
set -e

lscpu

module add orca

cd "$PBS_O_WORKDIR/$PBS_ARRAY_INDEX"

orca censo.inp > censo.out

orca vacuum_censo.inp > vacuum_censo.out
