#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=1Gb
#PBS -l ncpus=16
#PBS -l select=cputype=sapphirerapids
#PBS -j oe
set -e

lscpu

cd "${PBS_O_WORKDIR}"

/srv/scratch/${USER}/.namd_avx512/namd3 "+p$(nproc)" prod.namd > prod.log
