#!/usr/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=1G
#SBATCH --time=24:00:00

set -e

/software/projects/pawsey0265/mwang1/namd/namd3 +p16 prod.namd > prod.log
